[package]
name = "RustyTracer"
version = "0.1.0"
authors = ["Panu Akerman <panu.akerman@evident.fi>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
cgmath = "0.17.0"
image = "0.23.3"
